# Generated by Django 3.0 on 2020-03-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.TextField(max_length=6, null=True),
        ),
    ]
