# Generated by Django 3.0 on 2020-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBlog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=13, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Travel', 'Travel'), ('Coding', 'Coding'), ('Solo Trip', 'Solo Trip'), ('Food', 'Food')], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
