# Generated by Django 3.0 on 2020-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200428_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateBlog',
        ),
    ]
