# Generated by Django 3.0 on 2020-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_delete_createblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=13, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Travel', 'Travel'), ('Coding', 'Coding'), ('Solo Trip', 'Solo Trip'), ('Food', 'Food')], max_length=200, null=True)),
            ],
        ),
    ]
